import React from 'react';
export const Card = React.forwardRef(({ className = '', ...props }, ref) => (<div ref={ref} className={`rounded-xl border border-border bg-card text-card-foreground shadow-sm overflow-hidden transition-all duration-300 ${className}`} {...props}/>));
Card.displayName = 'Card';
export const CardHeader = React.forwardRef(({ className = '', ...props }, ref) => (<div ref={ref} className={`flex flex-col space-y-1.5 p-5 ${className}`} {...props}/>));
CardHeader.displayName = 'CardHeader';
export const CardTitle = React.forwardRef(({ className = '', ...props }, ref) => (<h3 ref={ref} className={`text-lg font-semibold leading-none tracking-tight ${className}`} {...props}/>));
CardTitle.displayName = 'CardTitle';
export const CardDescription = React.forwardRef(({ className = '', ...props }, ref) => (<p ref={ref} className={`text-sm text-muted-foreground ${className}`} {...props}/>));
CardDescription.displayName = 'CardDescription';
export const CardContent = React.forwardRef(({ className = '', ...props }, ref) => (<div ref={ref} className={`p-5 pt-0 ${className}`} {...props}/>));
CardContent.displayName = 'CardContent';
export const CardFooter = React.forwardRef(({ className = '', ...props }, ref) => (<div ref={ref} className={`flex items-center p-5 pt-0 border-t border-border/40 mt-auto ${className}`} {...props}/>));
CardFooter.displayName = 'CardFooter';
